dist: xenial
language: php
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
  - TASK_TESTS_COVERAGE=0

services:
- mysql

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
  - php: 7.4
    env: TASK_TESTS_COVERAGE=1
  - php: 7.3
  - php: 7.2
  - php: 7.1

install:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  fi

- travis_retry composer self-update
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
- sudo mysql_upgrade
- travis_retry mysql -e 'CREATE DATABASE `podiumtest`;'
- mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
- mysql -e "CREATE USER 'podium'@'localhost' IDENTIFIED BY 'podium';"
- mysql -e "GRANT ALL PRIVILEGES ON podiumtest.* TO 'podium'@'localhost';"
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
  fi

script:
- vendor/bin/phpunit -v

after_script:
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    travis_retry wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi
