sudo: required
language: php
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
  - TASK_TESTS_COVERAGE=0
services:
- mysql
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
matrix:
  fast_finish: true
  include:
  - php: 7.2
  - php: 7.1
    env: TASK_TESTS_COVERAGE=1

install:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    # disable xdebug for performance reasons when code coverage is not needed
    phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  fi

# install composer dependencies
- travis_retry composer self-update
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
# show some versions and env information
- php --version
- composer --version
- mysql --version
- sudo mysql_upgrade

# initialize databases
- travis_retry mysql -e 'CREATE DATABASE `podiumtest`;'
- mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
- mysql -e "CREATE USER 'podium'@'localhost' IDENTIFIED BY 'podium';"
- mysql -e "GRANT ALL PRIVILEGES ON podiumtest.* TO 'podium'@'localhost';"

# enable code coverage
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
  fi

script:
- vendor/bin/phpunit --verbose $PHPUNIT_FLAGS
