version: '3'
services:
  mysql5.7:
    restart: "no"
    image: mysql:5.7.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=podium
      - MYSQL_USER=podium
      - MYSQL_PASSWORD=podium
    tmpfs:
      - /var/lib/mysql/:rw
